### ISSUE TITLE
allow simple autocomplete (not only entity oriented)

### ISSUE THREAD

**Issue by Miwi35** [lifo101/typeahead-bundle#10]
Hi!
I Just wanted to say thank you for yor bundle first! it is really helpful!

However I found myself stucked with a small issue (not a bug).

The plugin works really well with entity type field but won't work with simple string.
What if I wanted to store a user name without storing the whole user entity?

With a __toString it will be stored but then in my edit form I will get an error saying:
"Expected argument of type "object or array", "string" given"

After investigation, the issue comes from the data transformers strongly coupled with the form Type. Maybe you could inject them via the service container or create a second formType called 'simple_typeahead' which would allow autocomplete based on entities (reverse transformation) but wouldn't try to reload the field based on an object but a string/int.

Another option is just to test if the initial data to transform is an entity in the transformer and if it's not, do nothing.

I'll see if I can contribute and submit you a pull request soon ^^.

Thanks again!

**Comment by lifo101** [comment]
This is actually being implemented right now. A new version will be pushed up soon.

**Comment by Miwi35** [comment]
Thanks a lot for your replies!
Unfortunately I didn't had time to submit anything to you. :(
I'm glad if it's useful for anybody ^^.
