### ISSUE TITLE
Callback example

### ISSUE THREAD

**Issue by nzurita** [lifo101/typeahead-bundle#11]
Can you give an example of using callback parameter? I tryed all these and nothing happens when I click an item:

        $builder
            ->add('the_list', 'entity_typeahead', array('label'  => 'A list',
                                                                   'class'  => 'AppBundle:TheList',
                                                                   'render' => 'name',
                                                                   'route'  => 'the_list',
                                                                   'mapped' => false,
                                                                   'callback' => 'alert(text)'
                                                                   ))

Also
    `'callback' => 'function(text, data) {alert(text);}'`

Nothing happens, no error, no action. I can see the attribute `data-callback="function(text, data) {alert(text);}"` is correctly set.

Also, I can't see the spinner when waiting response, maybe these problems are related

**Comment by lifo101** [comment]
That should be a string with the name of a javascript function within your template. For example, in a template I might the following function defined: 

```twig
{% block javascripts %}
    {{ parent() }}
    <script>
        function select_entity_callback(text, data) {
            alert("You selected: " + text);
        }
    </script>
{% endblock %}

```

And my form type would be defined as:

```php
$builder->add('the_list', 'entity_typeahead', array(
    'label'  => 'A list',
    'class'  => 'AppBundle:TheList',
    'render' => 'name',
    'route'  => 'the_list',
    'mapped' => false,
    'callback' => 'select_entity_callback'
))
```

**Comment by nzurita** [comment]
thanks

**Comment by lifo101** [comment]
np
