### ISSUE TITLE
Error including JS library

### ISSUE THREAD

**Issue by nzurita** [lifo101/typeahead-bundle#12]
Hello, when in PROD mode (strangely it works in DEV mode) I get this error in `prod.log`: 

> request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /js/lifo_typeahead.js" (from "http://example.com/example/new")" at /var/www/html/example/app/cache/prod/classes.php line 2512 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /js/lifo_typeahead.js\"

I guess it's related to this part of my code, that I copied from `README.md` without really understanding it:

        <script src="{{asset( '/js/bootstrap.min.js') }}" type="text/javascript"></script>
        {% javascripts filter='?yui_js' output='js/lifo_typeahead.js'
        '@lifo_typeahead_js'
        %}
        <script src="{{ asset_url }}"></script>

As a maybe related issue, I stripped out de `yui_css` part in next code due to another exception:

        {% stylesheets filter='cssrewrite' output='css/lifo_typeahead.css'
        '@lifo_typeahead_css'
        -%}
        <link href="{{ asset_url }}" type="text/css" rel="stylesheet" />
        {% endstylesheets %}

**Comment by lifo101** [comment]
Make sure you dump your assets: ```app/console assetic:dump --env prod --no-debug```
That will create the typeahead javascripts in your web directory. I failed to mention that in the install docs.
