### ISSUE TITLE
spinner is not showing

### ISSUE THREAD

**Issue by nzurita** [lifo101/typeahead-bundle#16]
Hello, everything is working ok, but spinner is never showing up, I tried to leave it as default or adding my own value like this one:

            ->add('code', 'entity_typeahead', array('required'  => false,
                                                    'label'     => Your code',
                                                    'class'     => 'AppBundle:TheCode',
                                                    'render'    => 'code',
                                                    'route'     => 'list_codes',
                                                    'callback'  => 'getCodeInfo',
                                                    'minLength' => 3,
                                                    'spinner'   => "fa fa-spinner"
                                                    ))

I'm running in `dev` mode so I don't think is an assets thing, and the rest of things are properly styled (I have font awesome library also)

Thank you

**Comment by lifo101** [comment]
I know this is really old, but better late than never. The spinner will work with Font-awesome icons now. In tag [v2.3.1](https://github.com/lifo101/typeahead-bundle/releases/tag/2.3.1)
