### ISSUE TITLE
Error when counting the response data from controller

### ISSUE THREAD

**Issue by berkbadem** [lifo101/typeahead-bundle#17]
I got the parsing error from javascript source of your code. 

my json output was like : 
[{"id":1,"value":"test"},{"id":2,"value":"test2"}]

and the success method of $.ajax acts like its string and it parsed all string like an array ( which is count of string ) 

I guess there were problem in intelligient guess method of jquery but just we can simply add 

dataType: "json",

into typeheadjs which under the $.ajax. This will fix the problem.

**Comment by lifo101** [comment]
Make sure your server response sets the header: `Content-Type: application/json`. That way the AJAX call will properly detect the json response w/o any code changes.
