### ISSUE TITLE
id null in form

### ISSUE THREAD

**Issue by fromdz27** [lifo101/typeahead-bundle#20]
hey,
i integrate your bundle in my project for using it as tag input.
but i get this error 
**

> "Impossible to access an attribute ("id") on a null variable in LifoTypeaheadBundle:Form:typeahead.html.twig at line 62."

**
i use symfony 2.7, this is my form code:
```
->add('tags', 'entity_typeahead', array(
                'class'  => 'WF\TagBundle\Entity\Tag',
                'render' => 'name',
                'route'  => 'wf_advert_tags',
                'multiple' => true
            ));

```

**Comment by lifo101** [comment]
Does your `Tag` entity have an `id` field? Try setting the `property` option to `name`:

```php
->add('tags', 'entity_typeahead', array(
                'class'  => 'WF\TagBundle\Entity\Tag',
                'property' => 'name',
                'render' => 'name',
                'route'  => 'wf_advert_tags',
                'multiple' => true
            ));
```

**Comment by fromdz27** [comment]
hey again,
i try `property` option to `name` but i had the same error ?
my Tag Entity had 02 fields: 'id' and 'name'
what's wrong,

**Comment by benstinton** [comment]
hi both, 
I've got the exact same issue. @fromdz27 I'd be grateful if you have any pointers to how you fixed this.
Ben
